#!/bin/bash
# bash createCluster $1=[projectID] $2=[clusterName] $3=[serviceAccount]

gcloud beta container --project $1 clusters create $2 \
 --zone us-central1-c --no-enable-basic-auth --cluster-version 1.14.10-gke.36 \
 --machine-type n1-standard-2 --image-type COS --disk-type pd-standard --disk-size 100 \
 --metadata disable-legacy-endpoints=true --service-account $3 \
 --preemptible --num-nodes 3 --enable-stackdriver-kubernetes --enable-ip-alias \
 --network projects/$1/global/networks/default \
 --subnetwork projects/$1/regions/us-central1/subnetworks/default --default-max-pods-per-node 110 \
 --enable-autoscaling --min-nodes 0 --max-nodes 3 --no-enable-master-authorized-networks \
 --addons HorizontalPodAutoscaling,HttpLoadBalancing --enable-autoupgrade --enable-autorepair \
 --max-surge-upgrade 1 --max-unavailable-upgrade 0 --identity-namespace $1.svc.id.goog

gcloud container clusters get-credentials $2

kubectl create serviceaccount --namespace default cluster-service

gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member serviceAccount:$1.svc.id.goog[default/cluster-service] \
  $3

kubectl annotate serviceaccount \
  --namespace default \
  cluster-service \
  iam.gke.io/gcp-service-account=$3


