#!/bin/bash
# bash createCluster $1=[projectID] $2=[clusterName] $3=[serviceAccount]

# ###### works due to service account - Not workload identity
# gcloud beta container clusters create $2 \
# --machine-type n1-standard-4
# --release-channel regular \
# --service-account $3
# ######



# ###### works due to scopes - Not workload identity
# gcloud beta container clusters create $2 \
#   --release-channel regular \
#   --scopes https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/userinfo.email
# ######



##### Works! Requires setting the service account on the deployment
gcloud beta container clusters create $2 \
  --release-channel regular \
  --identity-namespace $1.svc.id.goog

# 
gcloud container clusters get-credentials $2

kubectl create serviceaccount --namespace default cluster-service

gcloud iam service-accounts add-iam-policy-binding \
  --member serviceAccount:$1.svc.id.goog[default/cluster-service] \
  --role roles/iam.workloadIdentityUser \
  $3

kubectl annotate serviceaccount \
  --namespace default \
  cluster-service \
  iam.gke.io/gcp-service-account=$3
# ######